//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_stocks
    {
        public int id { get; set; }
        public string stock_name { get; set; }
        public Nullable<decimal> stock_price { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> stock_amount { get; set; }
        public string description { get; set; }
        public string username { get; set; }
        public string supplier_name { get; set; }
        public string action_type { get; set; }
        public Nullable<System.DateTime> action_time { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
    
        public virtual category category { get; set; }
    }
}
