//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_contacts
    {
        public int id { get; set; }
        public string email { get; set; }
        public string old_status { get; set; }
        public string new_status { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> changed_at { get; set; }
        public string message { get; set; }
    }
}
