//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_logs
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string status { get; set; }
    }
}
