//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public string stock_name { get; set; }
        public Nullable<decimal> stock_price { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> stock_amount { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
