//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryEntities : DbContext
    {
        public inventoryEntities()
            : base("name=inventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<history_contacts> history_contacts { get; set; }
        public virtual DbSet<history_stocks> history_stocks { get; set; }
        public virtual DbSet<history_suppliers> history_suppliers { get; set; }
        public virtual DbSet<history_suppliers_web> history_suppliers_web { get; set; }
        public virtual DbSet<login_logs> login_logs { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<suppliers_web> suppliers_web { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
